version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  browser-tools: circleci/browser-tools@1.4.0

workflows:
  version: 2
  default:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - install-mbx-ci:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
            branches:
              ignore: '/pull\/[0-9]*/'
      - build:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
            - install-mbx-ci
          filters:
            tags:
              only: '/v[0-9]+\.[0-9]+\.[0-9]+(\-dev)?/'
            branches:
              ignore: /.*/

defaults: &defaults
  docker:
    - image: cimg/node:18.12-browsers
  working_directory: ~/mapbox-gl-directions

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 'v1-npm-deps-{{ checksum "package-lock.json" }}'
      - run: npm ci
      - save_cache:
          key: 'v1-npm-deps-{{ checksum "package-lock.json" }}'
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - .ssh
            - mapbox-gl-directions

  install-mbx-ci:
    <<: *defaults
    steps:
      - run:
          name: Install mbx-ci
          command: |
            curl -Ls https://mapbox-release-engineering.s3.amazonaws.com/mbx-ci/latest/mbx-ci-linux-amd64 > ~/mbx-ci &&
            chmod 755 ~/mbx-ci
      - persist_to_workspace:
          root: ~/
          paths:
            - .ssh
            - .aws
            - mbx-ci

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: ~/
          paths:
            - mapbox-gl-directions/dist

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - 'v2-lint-{{ .Branch }}'
            - v2-lint
      - run: npm run lint
      - save_cache:
          key: 'v2-lint-{{ .Branch }}-{{ .Revision }}'
          paths:
            - .eslintcache

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - browser-tools/install-firefox
      - run: npm run test

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/install
      - run:
          name: Setup AWS
          command: |
             ~/mbx-ci aws setup
      - run: >-
          aws s3 cp --recursive --acl public-read dist s3://mapbox-gl-js/plugins/mapbox-gl-directions/$CIRCLE_TAG
