export const SET_OPTIONS = 'SET_OPTIONS';

export const ORIGIN = 'ORIGIN';
export const DESTINATION = 'DESTINATION';

export const ORIGIN_INPUT = 'ORIGIN_INPUT';
export const DESTINATION_INPUT = 'DESTINATION_INPUT';

export const ORIGIN_CLEAR = 'ORIGIN_CLEAR';
export const DESTINATION_CLEAR = 'DESTINATION_CLEAR';

export const REVERSE_INPUTS = 'REVERSE_INPUTS';

export const ORIGIN_COORDINATES = 'ORIGIN_COORDINATES';
export const DESTINATION_COORDINATES = 'DESTINATION_COORDINATES';

export const DIRECTIONS = 'DIRECTIONS';
export const DIRECTIONS_PROFILE = 'DIRECTIONS_PROFILE';

export const HOVER_MARKER = 'HOVER_MARKER';

export const ROUTE_INDEX = 'ROUTE_INDEX';

export const HOVER_WAYPOINT = 'HOVER_WAYPOINT';
export const WAYPOINTS = 'WAYPOINTS';
export const REDUCE_WAYPOINTS = 'REDUCE_WAYPOINTS';
