export const ORIGIN_INPUT = 'ORIGIN_INPUT';
export const DESTINATION_INPUT = 'DESTINATION_INPUT';

export const ORIGIN_CLEAR = 'ORIGIN_CLEAR';
export const DESTINATION_CLEAR = 'DESTINATION_CLEAR';

export const REVERSE_INPUTS = 'REVERSE_INPUTS';

export const ORIGIN_COORDINATES = 'ORIGIN_COORDINATES';
export const DESTINATION_COORDINATES = 'DESTINATION_COORDINATES';

export const DIRECTIONS = 'DIRECTIONS';
export const GEOJSON = 'GEOJSON';
